### ISSUE TITLE
stop working since 26/3/2022

### ISSUE THREAD

**Issue by divemasterjm** [evanjd/python-logi-circle#10]
Hi, since 26/3/2022 i've got the following error while in HA is working the integration
Traceback (most recent call last):
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 42, in login
    await self._restore_cached_session()
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 116, in _restore_cached_session
    raise BadCache()
logi_circle.exception.BadCache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proxmoxha/prueba.py", line 29, in <module>
    loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/proxmoxha/prueba.py", line 16, in run
    my_camera = (await logi_api.cameras)[0]
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 190, in cameras
    raw_cameras = await self._fetch(CAMERAS_ENDPOINT)
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 137, in _fetch
    await self.login()
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 45, in login
    await self._authenticate()
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/logi_circle/__init__.py", line 74, in _authenticate
    req.raise_for_status()
  File "/home/proxmoxha/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://video.logi.com/api/accounts/authorization')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0024bef198>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f0024b985f8>, 3886427.412803758)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f0024bef048>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0024bef160>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f0024b98a08>, 3886428.140641346)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f0024be8c18>

**Comment by divemasterjm** [comment]
@evanjd any idea?

**Comment by evanjd** [comment]
Hi @divemasterjm, this is fixed in [version 0.1.9](https://pypi.org/project/logi-circle/0.1.9/).

**Comment by divemasterjm** [comment]
> Hi @divemasterjm, this is fixed in [version 0.1.9](https://pypi.org/project/logi-circle/0.1.9/).

works, thanks!!!!
