### ISSUE TITLE
Still having login failure with 0.1.9 version

### ISSUE THREAD

**Issue by deepcoder** [evanjd/python-logi-circle#15]
I have removed .logi_circle-session.cache file and am pretty sure I running latest version 0.1.9 of:
https://github.com/evanjd/python-logi-circle/tree/private-api

any ideas on how I can generate more info and make progress?

Thx!

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 42, in login
    await self._restore_cached_session()
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 124, in _restore_cached_session
    raise BadCache()
logi_circle.exception.BadCache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_login.py", line 13, in <module>
    loop.run_until_complete(get_snapshot_images())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./test_login.py", line 8, in get_snapshot_images
    for camera in await logi_api.cameras:
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 190, in cameras
    raw_cameras = await self._fetch(CAMERAS_ENDPOINT)
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 137, in _fetch
    await self.login()
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 45, in login
    await self._authenticate()
  File "/home/user/.local/lib/python3.8/site-packages/logi_circle/__init__.py", line 70, in _authenticate
    raise BadLogin(
logi_circle.exception.BadLogin: Username or password provided is incorrect. Could not authenticate.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f66f527af10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f66f523ff40>, 90.151481007)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f66f5202df0>
```

**Comment by r4nt** [comment]
I've got the same problem; given Logi is not handing out API keys any more this would be great to get to work.

**Comment by mathieucarbou** [comment]
same issue. Would like to know 😭

**Comment by evanjd** [comment]
Hi all. I took a quick look, and it appears Logitech have switched to OAuth2 on their private API, breaking this integration (and as best as I can tell, all others). It may be possible to workaround this (eg. using a headless browser to intercept the auth code), however:

- It would require more effort than I'm prepared to give right now
- It would be brittle and could be easily broken when Logitech change anything

If anyone wants to contribute a fix, I'd welcome it. Or if anyone can point me to a working integration with Logi's private API, I'd happily consider porting it. In the meantime, I've updated the README on the private-api branch to indicate that this is currently broken.

Sorry all.
